### PR TITLE
xaie_helper.c : fix calloc error with GCC 14

### PR DESCRIPTION
**Pull request by Byvirven**
Fix transposed calloc arguments for compatibility with GCC 14
    
Corrected the order of arguments in calloc calls in `xaie_helper.c` to resolve
compilation errors with GCC 14.2.1 (`-Werror=calloc-transposed-args`).

- Updated `XAie_Txn_MergeSync` to use `calloc(1, sizeof(tct_op_t))`.
- Updated `XAie_Txn_DdrAddressPatch` to use `calloc(1, sizeof(patch_op_t))`.

**Problem solved by the commit**

These changes eliminate errors caused by transposed arguments GCC 14 with the calloc function,
ensuring proper memory allocation and alignment. In previous versions of GCC, this was a simple 
warning but now it is critical errors.

**Bug / issue (if any) fixed, which PR introduced the bug, how it was discovered**

The problem was identified while attempting to compile xdna-driver with GCC 14.2.1 under 
Fedora 41 with kernel 6.11.8

**How problem was solved, alternative solutions (if any) and why they were rejected**

The first solution to fix the problem is to use the "-disable-werror" argument of the build.sh script 
when compiling xdna npu-xrt library.

The second solution, more stable, has to respect the order of the calloc parameters (the number of 
consecutive elements to allocate and the size of an element, in our case, a struct), therefore 1x8 bytes 
in the first one and 1x36 bytes the second one instead of 8x1 and 36x1.

**Risks (if any) associated the changes in the commit**

The risks are minimal and it has been adopted in different branches.

**What has been tested and how, request additional testing if necessary**

- Success build with GCC 14.2.1 of XDNA drivers under Fedora 41 powered by kernel 6.11.8
- Basic XDNA test files passed with success

**Documentation impact (if any)**

I'ld be delighted if any real documentation was available...

### CODE REVIEW

**Comment by keryell** [comment]
This sounds like a duplicate of https://github.com/Xilinx/aie-rt/pull/11
